### ISSUE TITLE
Error in Connect()

### ISSUE THREAD

**Issue by elyfran** [steavy29/Telegram.Net#2] opened 2016-09-21 14:45 UTC
I'm assigning all parameters correctly and is occurring error connecting .

Stacktrace: TLSharp.Core.TelegramClient.<SendCodeRequest>d__13.MoveNext() 

In the Teste only run AuthenticationWorks, DataCenterMigrationErrorHandling and TestConnection the others are in error.

Do u can help me?

**Comment by steavy29** [comment] 2016-09-21 18:53
Please, paste some code which causes error and the error itself. Most likely tests fail because you didn't filled configuration values in `app.config`.

**Comment by elyfran** [comment] 2016-09-21 18:58
first ran the tests with the credentials that are configured in app.config and then tested it with my credentials . the credentials already entered are valid ?

**Comment by elyfran** [comment] 2016-09-21 19:00
These settings are valid ?

`  <appSettings>
    <add key="ApiId" value="65386"/>
    <add key="ApiHash" value="bd557adc23ae98b04cfc37b08f471149"/>
    <add key="NumberToAuthenticate" value="380999608954"/>
    <add key="NotRegisteredNumberToSignUp" value=""/>
    <add key="NumberToSendMessage" value="380667352918"/>
    <add key="UserNameToSendMessage" value="alphary_test"/>
    <add key="NumberToGetUserFull" value="380999608954"/>
    <add key="NumberToAddToChat" value=""/>
  </appSettings>`

**Comment by elyfran** [comment] 2016-09-21 19:38
- how can i make the "code"? (var code = ""; // you can change code in debugger)
this code is sent to my device?

- how should I write the number for authentication ?
+55 88 99999999 = 558899999999 or only 8899999999?

+55 = DDI
88 = DDD
99999999 = number

**Comment by steavy29** [comment] 2016-09-21 21:08
Please, update your sources. And please don't use current config. You should provide your own config numbers. Only then you'll be able to get the code you need for authentication.
Re. number: try number format without +

**Comment by elyfran** [comment] 2016-09-21 21:40
@steavy29 

The exception referred to PHONE_MIGRATE_1 ?

**Comment by elyfran** [comment] 2016-09-21 21:56
PHONE_MIGRATE_X: the phone number a user is trying to use for authorization is associated with a different data center.

???

**Comment by steavy29** [comment] 2016-09-21 21:58
Please show your config and code.

**Comment by elyfran** [comment] 2016-09-21 22:00
`
  <appSettings>
    <add key="ApiId" value="50570"/>
    <add key="ApiHash" value="2f3edb93b94bee1fdf261d1ddea4ba8c"/>
    <add key="NumberToAuthenticate" value="5585997972111"/>
    <add key="NotRegisteredNumberToSignUp" value=""/>
    <add key="NumberToSendMessage" value="5585986684299"/>
    <add key="UserNameToSendMessage" value=""/>
    <add key="NumberToGetUserFull" value="5585997972111"/>
    <add key="NumberToAddToChat" value=""/>
  </appSettings>
`

**Comment by steavy29** [comment] 2016-09-21 22:01
Do you receive code or error happens even before that?

**Comment by elyfran** [comment] 2016-09-21 22:02
i receved the code.

**Comment by elyfran** [comment] 2016-09-21 22:02
I am running the test AuthUser().

**Comment by steavy29** [comment] 2016-09-21 22:07
I`m running the same test with your config. Can you send me the code you just received?

**Comment by elyfran** [comment] 2016-09-21 22:07
79532

**Comment by elyfran** [comment] 2016-09-21 22:08
I received another sms with: 61248

**Comment by elyfran** [comment] 2016-09-21 22:11
now: 38270

**Comment by steavy29** [comment] 2016-09-21 22:13
Ok. I've reproduced exception in protocol with your configuration. Can I use it tomorrow morning to fix the issue?

**Comment by elyfran** [comment] 2016-09-21 22:14
Sure. no problem.

**Comment by steavy29** [comment] 2016-09-21 22:15
Fine. I'll update status tomorrow then.

**Comment by elyfran** [comment] 2016-09-21 22:24
I'll be waiting.
thx ;D

**Comment by elyfran** [comment] 2016-09-21 22:31
now receved : 71457

**Comment by elyfran** [comment] 2016-09-21 22:46
Now; 72267

**Comment by steavy29** [comment] 2016-09-21 22:47
I`ve pushed fix. Please check it out

**Comment by elyfran** [comment] 2016-09-21 22:51
OK. I will now test

**Comment by elyfran** [comment] 2016-09-21 22:55
Working perfectly. =D

**Comment by steavy29** [comment] 2016-09-21 23:02
Great. Thanks for reaching me here with this issue.

**Closed** 2016-09-21 23:03 UTC

**Comment by elyfran** [comment] 2016-09-21 23:28
Now that this problem: AUTH_KEY_UNREGISTERED. 

I am using the method : ImportContactByPhoneNumberAndSendMessage.
